teleop_twist_joy:
  ros__parameters:
    enable_button: 5       # RB (F710 X-mode default)
    enable_turbo_button: 4  # LB
    axis_linear:
      x: 1                 # left stick vertical
    scale_linear:
      x: 0.6
    scale_linear_turbo:
      x: 1.0
    axis_angular:
      yaw: 0               # left stick horizontal
    scale_angular:
      yaw: 1.2
    scale_angular_turbo:
      yaw: 2.0
    require_enable_button: true
    deadzone: 0.05
    autorepeat_rate: 20.0
