<?xml version="1.0"?>
<package format="3">
  <name>jetson_anomaly_detector</name>
  <version>0.1.0</version>
  <description>ROS 2 companion node for camera-based anomaly events on Jetson.</description>
  <maintainer email="sijakf3@gmail.com">Filip Sijak</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_python</buildtool_depend>

  <depend>rclpy</depend>
  <depend>sensor_msgs</depend>
  <depend>std_msgs</depend>
  <depend>cv_bridge</depend>

  <exec_depend>python3-opencv</exec_depend>
  <exec_depend>python3-yaml</exec_depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
